name: deploy
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }} 
          username: ${{ secrets.USERNAME }} 
          host: ${{ secrets.SERVER }} 
          command : ls