name: deploy
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }} 
          username: enta12
          host: ligne7.pepintrie.fr
          command : ls